version: '3'

services:
        dbos:
                image: mysql:5.7
                volumes:
                        - web_db:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_USER: radha
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mynewdb

        joomos:
                image: joomla
                restart: always
                depends_on:
                        - dboss
                ports:
                        - 9090:80
                environment:
                        JOOMLA_DB_HOST: mydataabse
                        JOOMLA_DB_USER: radha
                        JOOMLA_DB_PASSWORD: redhat
                        JOOMLA_DB_NAME: mynewdb
                volumes:
                        - joomvol:/var/www/html

volumes:
        webdb:
        joomvol:
